#pragma once
#include "serial_radarAPI_if.h"
#include "Config.h"

void *serialRadar(void *x_void_ptr);
void *spiUSB(void *x_void_ptr);
void *spiInit();
void spiClose();
iSYSResult_t initRadar(Config *cfg,bool populate);
iSYSResult setRadarConfig(bool update);

iSYSResult stopAcquisition();
iSYSResult startAcquisition();

extern bool start_acquisition;
extern bool stop_acquisition;


const char ERROR_CODES[][40] = {
	"ERR_OK",
	"ERR_FUNCTION_DEPRECATED",
	"ERR_DLL_NOT_FINISHED",
	"ERR_HANDLE_NOT_INITIALIZED",
	"ERR_COMPORT_DOESNT_EXIST",
	"ERR_COMPORT_CANT_INITIALIZE",
	"ERR_COMPORT_ACCESS_DENIED",
	"ERR_COMPORT_BAUDRATE_NOT_VALID",
	"ERR_COMPORT_CANT_OPEN",
	"ERR_COMPORT_CANT_SET_FLOW_CONTROL",
	"ERR_COMPORT_CANT_SET_PARITY",
	"ERR_COMPORT_CANT_SET_STOP_BITS",
	"ERR_COMPORT_CANT_SET_DATA_BITS",
	"ERR_COMPORT_CANT_SET_BAUDRATE",
	"ERR_COMPORT_ALREADY_INITIALIZED",
	"ERR_COMPORT_EQUALS_NULL",
	"ERR_COMPORT_NOT_OPEN",
	"ERR_COMPORT_NOT_READABLE",
	"ERR_COMPORT_NOT_WRITEABLE",
	"ERR_COMPORT_CANT_WRITE",
	"ERR_COMPORT_CANT_READ",
	"ERR_COMMAND_NOT_WRITTEN ",
	"ERR_COMMAND_NOT_READ",
	"ERR_COMMAND_NO_DATA_RECEIVED",
	"ERR_COMMAND_NO_VALID_FRAME_FOUND",
	"ERR_COMMAND_RX_FRAME_DAMAGED",
	"ERR_COMMAND_FAILURE",
	"ERR_UNDEFINED_READ",
	"ERR_COMPORT_LESS_DATA_READ",
	"ERR_COMPORT_SYSTEM_INIT_FAILED",
	"ERR_COMPORT_SYSTEM_ALREADY_INITIALIZED",
	"ERR_COMMAND_RX_FRAME_LENGTH",
	"ERR_COMMAND_MAX_DATA_OVERFLOW",
	"ERR_COMMAND_MAX_IQPAIRS_OVERFLOW",
	"ERR_COMMAND_NOT_ACCEPTED",
	"ERR_NULL_POINTER",
	"ERR_CALC_CORRECTION_PARAMS",
	"ERR_PARAMETER_OUT_OF_RANGE"
};

enum {
	LIST_BEGIN = 0
	, LIST_START
	, LIST_PROCESSING
	, LIST_END
	, LIST_ERROR
};



